configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - ".moban.d"
  configuration: pyexcel-handsontable.yml
targets:
  - README.rst: README.rst
  - setup.py: setup.py
  - requirements.txt: requirements.txt
  - LICENSE: LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - test.sh: test.sh.jj2
  - test.bat: test.sh.jj2
  - .gitignore: .gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - "pyexcel_handsontable/htmlwidgets/css.py": "handsontable/css.py"
  - "docs/source/index.rst": "docs/source/index.rst"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "tests/fixtures/book.handsontable.html": "tests/fixtures/book.handsontable.html"
  - "tests/fixtures/sheet_rendering.html": "tests/fixtures/sheet_rendering.html"
